import type { StorageBrowserDisplayText } from "@aws-amplify/ui-react-storage/browser";

const jaDateFormat = new Intl.DateTimeFormat("ja-JP", {
  year: "numeric",
  month: "2-digit",
  day: "2-digit",
  hour: "2-digit",
  minute: "2-digit",
  hourCycle: "h23",
});

export const jaDisplayText: StorageBrowserDisplayText = {
  LocationsView: {
    title: "ホーム",
    searchPlaceholder: "フォルダとファイルを検索",
    searchSubmitLabel: "検索",
    searchClearLabel: "検索をクリア",
    loadingIndicatorLabel: "読み込み中",
    tableColumnFolderHeader: "フォルダ",
    tableColumnBucketHeader: "バケット",
    tableColumnPermissionsHeader: "権限",
    tableColumnActionsHeader: "操作",
    getPermissionName: (permissions) => {
      const canRead =
        permissions.includes("get") || permissions.includes("list");
      const canWrite =
        permissions.includes("write") || permissions.includes("delete");
      if (canRead && canWrite) return "読み書き";
      if (canRead) return "読み取り";
      if (canWrite) return "書き込み";
      return permissions.join("/");
    },
    getDownloadLabel: (fileName) => `${fileName} をダウンロード`,
    getDateDisplayValue: (date) => jaDateFormat.format(date),
  },
  LocationDetailView: {
    searchPlaceholder: "現在のフォルダ内を検索",
    searchSubfoldersToggleLabel: "サブフォルダを含む",
    searchSubmitLabel: "検索",
    searchClearLabel: "検索をクリア",
    loadingIndicatorLabel: "読み込み中",
    selectFileLabel: "ファイルを選択",
    selectFolderLabel: "フォルダを選択",
    selectAllFilesLabel: "全てのファイルを選択",
    tableColumnNameHeader: "名前",
    tableColumnSizeHeader: "サイズ",
    tableColumnTypeHeader: "種類",
    tableColumnLastModifiedHeader: "更新日時",
    getDateDisplayValue: (date) => jaDateFormat.format(date),
    getActionListItemLabel: (key = "") => {
      const labels: Record<string, string> = {
        Copy: "コピー",
        Delete: "削除",
        "Create folder": "フォルダ作成",
        Upload: "アップロード",
        Download: "ダウンロード",
      };
      return labels[key] ?? key;
    },
    filePreview: {
      closeButtonLabel: "閉じる",
      filePreviewTitle: "ファイルプレビュー",
      fileInformationTitle: "ファイル情報",
      errorMessage: "エラーが発生しました",
      sizeLimitMessage: "プレビューサイズの上限を超えています",
      unsupportedFileMessage: "このファイル形式のプレビューには対応していません",
      keyLabel: "キー",
      sizeLabel: "サイズ",
      versionIdLabel: "バージョン ID",
      lastModifiedLabel: "更新日時",
      entityTagLabel: "エンティティタグ",
      typeLabel: "種類",
      unknownValue: "不明",
      errorDescription:
        "ファイルプレビューの読み込み中に問題が発生しました。",
      unsupportedFileDescription:
        "このファイル形式はプレビューに対応していません。ダウンロードしてご確認ください。",
      imageLoadErrorDescription:
        "画像を読み込めませんでした。ネットワークの問題、ファイルの破損、または未対応の画像形式の可能性があります。",
      videoLoadErrorDescription:
        "動画を再生できませんでした。ネットワークの問題、ファイルの破損、または未対応の動画形式の可能性があります。",
      textLoadErrorDescription:
        "テキストファイルを読み込めませんでした。ネットワークの問題、アクセス権限、またはファイルサイズが大きすぎる可能性があります。",
      generalPreviewErrorDescription:
        "プレビューの読み込み中に予期しないエラーが発生しました。再試行するか、ダウンロードしてご確認ください。",
      fileSizeLimitDescription:
        "このファイルはブラウザでプレビューするには大きすぎます。ダウンロードしてご確認ください。",
      filePrefix: "ファイル: ",
      retryButtonLabel: "再試行",
      downloadButtonLabel: "ダウンロード",
      getTextErrorMessage: (error) => `ファイル読み込みエラー: ${error}`,
      emptyFileMessage: "ファイルは空です",
    },
  },
  UploadView: {
    title: "アップロード",
    actionStartLabel: "アップロード",
    actionCancelLabel: "キャンセル",
    actionExitLabel: "閉じる",
    actionDestinationLabel: "アップロード先",
    addFilesLabel: "ファイルを追加",
    addFolderLabel: "フォルダを追加",
    overwriteToggleLabel: "既存ファイルを上書き",
    statusDisplayCanceledLabel: "キャンセル済み",
    statusDisplayCompletedLabel: "完了",
    statusDisplayLoadedLabel: "完了",
    statusDisplayFailedLabel: "失敗",
    statusDisplayInProgressLabel: "処理中",
    statusDisplayFinishingLabel: "処理中",
    statusDisplayQueuedLabel: "未開始",
    statusDisplayTotalLabel: "合計",
    statusDisplayOverwritePreventedLabel: "上書き防止",
    tableColumnCancelHeader: "",
    tableColumnStatusHeader: "状態",
    tableColumnFolderHeader: "フォルダ",
    tableColumnNameHeader: "名前",
    tableColumnTypeHeader: "種類",
    tableColumnSizeHeader: "サイズ",
    tableColumnProgressHeader: "進捗",
  },
  DownloadView: {
    title: "ダウンロード",
    actionStartLabel: "ダウンロード",
    actionCancelLabel: "キャンセル",
    actionExitLabel: "閉じる",
    actionDestinationLabel: "ダウンロード先",
    statusDisplayCanceledLabel: "キャンセル済み",
    statusDisplayCompletedLabel: "完了",
    statusDisplayLoadedLabel: "読み込み完了",
    statusDisplayFailedLabel: "失敗",
    statusDisplayInProgressLabel: "処理中",
    statusDisplayFinishingLabel: "圧縮中",
    statusDisplayQueuedLabel: "未開始",
    statusDisplayTotalLabel: "合計",
    tableColumnCancelHeader: "",
    tableColumnStatusHeader: "状態",
    tableColumnFolderHeader: "フォルダ",
    tableColumnNameHeader: "名前",
    tableColumnTypeHeader: "種類",
    tableColumnSizeHeader: "サイズ",
    tableColumnProgressHeader: "進捗",
  },
  CopyView: {
    title: "コピー",
    actionStartLabel: "コピー",
    actionCancelLabel: "キャンセル",
    actionExitLabel: "閉じる",
    actionDestinationLabel: "コピー先",
    // @ts-expect-error ライブラリの型定義が 'Loading' リテラルを要求するバグ。実行時は string として扱われる
    loadingIndicatorLabel: "読み込み中",
    overwriteWarningMessage:
      "コピー先に同名のファイルが存在する場合は上書きされます。",
    searchPlaceholder: "フォルダを検索",
    searchSubmitLabel: "検索",
    searchClearLabel: "検索をクリア",
    statusDisplayCanceledLabel: "キャンセル済み",
    statusDisplayCompletedLabel: "完了",
    statusDisplayLoadedLabel: "完了",
    statusDisplayFailedLabel: "失敗",
    statusDisplayInProgressLabel: "処理中",
    statusDisplayFinishingLabel: "処理中",
    statusDisplayQueuedLabel: "未開始",
    statusDisplayTotalLabel: "合計",
    tableColumnCancelHeader: "",
    tableColumnStatusHeader: "状態",
    tableColumnFolderHeader: "フォルダ",
    tableColumnNameHeader: "名前",
    tableColumnTypeHeader: "種類",
    tableColumnSizeHeader: "サイズ",
  },
  DeleteView: {
    title: "削除",
    actionStartLabel: "削除",
    actionCancelLabel: "キャンセル",
    actionExitLabel: "閉じる",
    actionDestinationLabel: "削除先",
    confirmationModalTitle: "削除の確認",
    confirmationModalConfirmLabel: "削除",
    confirmationModalCancelLabel: "キャンセル",
    confirmationModalMessage:
      "削除対象に {count} 件のフォルダが含まれています",
    confirmationModalFolderListTitle: "フォルダ一覧:",
    statusDisplayCanceledLabel: "キャンセル済み",
    statusDisplayCompletedLabel: "完了",
    statusDisplayLoadedLabel: "完了",
    statusDisplayFailedLabel: "失敗",
    statusDisplayInProgressLabel: "処理中",
    statusDisplayFinishingLabel: "処理中",
    statusDisplayQueuedLabel: "未開始",
    statusDisplayTotalLabel: "合計",
    tableColumnCancelHeader: "",
    tableColumnStatusHeader: "状態",
    tableColumnFolderHeader: "フォルダ",
    tableColumnNameHeader: "名前",
    tableColumnTypeHeader: "種類",
    tableColumnSizeHeader: "サイズ",
  },
  CreateFolderView: {
    title: "フォルダ作成",
    actionStartLabel: "フォルダを作成",
    actionCancelLabel: "キャンセル",
    actionExitLabel: "閉じる",
    actionDestinationLabel: "作成先",
    folderNameLabel: "フォルダ名",
    folderNamePlaceholder:
      'フォルダ名に "/" は使えません。また "." で開始 / 終了することはできません',
    getValidationMessage: () =>
      'フォルダ名に "/" は使えません。また "." で開始 / 終了することはできません',
  },
};
